### ISSUE TITLE
Space Types - Move without permission

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-enterprise-theme#18]
- Create multiple Space types A & B 
- Allow `Users` group to only create Spaces of Type `B`

User can create `B` Space and change Type to `A`

![image](https://user-images.githubusercontent.com/4736168/108981901-804e1800-768d-11eb-9248-60cca0926897.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in MR https://git.humhub.org/professional/enterprise-theme/-/merge_requests/3

**Comment by luke-** [comment]
Thanks!
