### ISSUE TITLE
Visibility of space categories in navigation

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub-modules-enterprise-theme#28]
HH 1.15.3
EE 1.11.3

User: 

- No membership in space of space category
- No permission to create space in category 

Space: 

- Option to show space in directory not selected

--> Space category appears in navigation, which it should not

If a user is not a member of a space of a category and does not have the permission to create a space in that category, the category should not appear in the navigation by default. 

In addition to that, we should introduce a new option in the space category settings to enable admins to reverse this behaviour. Checkbox "Show category in navigation even if empty"

![image](https://github.com/humhub/enterprise-theme-issues/assets/38326726/5a43acba-f8dd-4acf-9dd6-f32e953de24e)

**Comment by yurabakhtin** [comment]
@luke- @Semir1212 PR https://github.com/humhub/enterprise-theme/pull/62.
