### ISSUE TITLE
How do we reload left-navigation?

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub-modules-enterprise-theme#5]
Hi,
I troubled with directory -> follow ... When I press the space's  "Follo" button, but left-navigation does not change the list. We must go logout and return. It is troublesome.
It is happy if you enhance the draw function which left-navigation reload with selection of Follow/Unfollow.
Thank you.

**Comment by buddh4** [comment]
If I understand correctly, you have space menu items which are only visible for users following a space?

**Comment by buddh4** [comment]
I've opened an issue at the core since this also affects the community theme: https://github.com/humhub/humhub/issues/4281
