### ISSUE TITLE
Limit OEmbed/Youtube Video Size

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-enterprise-theme#9]

**Comment by MasterHans** [comment]
@luke-  could you please give me a hint about where is the OEmbed/Youtube in humhub? where I can add OEmbed/Youtube?

**Comment by MasterHans** [comment]
Hello everyone,

@luke-  could you please guide me to where in humhub the OEmbed/Youtube Video is?
Is it in the THEME in the humhub-modules-enterprise-theme ? If that so where could I find it to review?

**Comment by luke-** [comment]
@MasterHans For example, if you post a Youtube link in a post, a Youtube player should be added.

Since the Enterprise Theme is designed for 100% width, the player often becomes very large. We have to find a size limit here.

**Comment by MasterHans** [comment]
> @MasterHans For example, if you post a Youtube link in a post, a Youtube player should be added.
> 
> Since the Enterprise Theme is designed for 100% width, the player often becomes very large. We have to find a size limit here.

I see thank you ...
Where could I find Enterprise Theme?

In this repository readme only...

**Comment by buddh4** [comment]
Just found this library, maybe we could use this also in the core: http://fitvidsjs.com/ did not have a closer look though. 
We should test/apply this to the following embeds:

- Youtube (oembed)
- Vimeo (oembed)
- Attached videos
- Any other ideas?

**Comment by luke-** [comment]
Fitvidsjs looks very promising!

**Comment by MasterHans** [comment]
I found this hint:
Vimeo Autoplay API is not compatible with FitVids in IE11. You must manually wrap videos you want to autoplay

**Comment by buddh4** [comment]
We do not support ie11 anymore but i think it wont totally break ie

**Comment by MasterHans** [comment]
> Just found this library, maybe we could use this also in the core: http://fitvidsjs.com/ did not have a closer look though.
> We should test/apply this to the following embeds:
> 
> * Youtube (oembed)
> * Vimeo (oembed)
> * Attached videos
> * Any other ideas?

Looks like we couldn't use this library because fitvidsjs works only with iframes, and object and embed tags.

for example like this:

```
<div class="vendor">
        	<iframe width="425" height="349" src="http://www.youtube.com/embed/FKWwdQu6_ok" frameborder="0" allowfullscreen></iframe>
	      </div>
	      <div class="vendor">
        	<iframe src="http://player.vimeo.com/video/25708134?title=0&amp;byline=0&amp;portrait=0" width="400" height="225" frameborder="0"></iframe>
        </div>
        <div class="vendor">
        	<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="437" height="288" id="viddler"><param name="movie" value="http://www.viddler.com/player/d6c37b62/" /><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="true" /><param name="flashvars" value="fake=1"/><embed src="http://www.viddler.com/player/d6c37b62/" width="437" height="288" type="application/x-shockwave-flash" allowScriptAccess="always" allowFullScreen="true" flashvars="fake=1" name="viddler" ></embed></object>
        </div>
        <div class="vendor">
        	<embed src="http://blip.tv/play/AYHCnikC" type="application/x-shockwave-flash" width="550" height="396" wmode="transparent" allowscriptaccess="always" allowfullscreen="true" ></embed>
        </div>
```


Our embedded video with the current video player did not build this tags...

**Comment by luke-** [comment]
@buddh4 Can you take a look here? Or would that be more of an issue for you?

**Comment by buddh4** [comment]
@MasterHans embedded youtube videos etc. should also use iframes, I'll do some testing. Or did you already do some other work related to this issue?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/enterprise-theme/pull/16: I have implemented new module settings to limit video width by CSS:

<img width="1037" alt="test_video_size" src="https://user-images.githubusercontent.com/6995524/128183695-1c46d6bb-333a-4bad-9a80-62dcc8e6a223.png">

**Comment by luke-** [comment]
@yurabakhtin Cool solution! Is there also a default value set here? Is the video always centered? I think right-aligned would be a bit nicer.

**Comment by yurabakhtin** [comment]
@luke- 

> Is there also a default value set here?

As I wrote in the fields hint default values:

- Video width: 100%
- Video ratio: 16:9

> Is the video always centered? I think right-aligned would be a bit nicer.

Yes, I specially did it, because I thought it nicer than right. Should I revert that back?

**Comment by luke-** [comment]
@orangiene Can you please choose the alignment and the maximum width for the Enterprise Theme?

**Comment by orangiene** [comment]
![Community-Layout-Video](https://user-images.githubusercontent.com/62644500/139294617-aaf63798-987a-4d02-93c1-f96d85dac73f.jpg)
![Enterprise-Layout-Video](https://user-images.githubusercontent.com/62644500/139294622-9b30273a-5348-4ada-a97f-e91acebf255c.jpg)

hello :)

I would suggest that we stay with the 16:9 format and center the video.
For Community a width of 500px and for Enterprise 940px.
@yurabakhtin , can you please test if this is small enough so that the video is not cropped? 
Thanks a lot, it's not urgent :)

**Comment by yurabakhtin** [comment]
@orangiene 

> can you please test if this is small enough so that the video is not cropped?

Fixed in commit https://github.com/humhub/enterprise-theme/pull/16/commits/020d6e713a95ff343d1d1de8ee5d9ef72a2f522d:

<img width="2559" alt="video_width" src="https://user-images.githubusercontent.com/6995524/145391088-5ece50fc-d3d7-4d17-9c35-c25350f16f24.png">

**Comment by orangiene** [comment]
in safari it looks good, unfortunately not in chrome. 
I have already cleared the cache and logged in again.
@luke- , can you please check again?

**Comment by yurabakhtin** [comment]
@orangiene My above screenshots were done from Chrome, please show what issue you have on your side.

**Comment by luke-** [comment]
@orangiene Can you please try again?

**Comment by orangiene** [comment]
now it works. thank you :)
